# Site settings
title: Smokey Robinson

sections:
    - title: home
    - title: about
    - title: food
    - title: menu
    - title: contact

contact:
    facebook:
        black: /images/fb-black.png
    mail:
        black: /images/mail-black.png

# Build settings
markdown: kramdown
