# Site settings
title: Smokey Robinson

sections:
    - title: home
    - title: about
    - title: food
    - title: menu
    - title: contact

contact:
    facebook:
        black: /images/fb-black.png
    mail:
        black: /images/mail-black.png

carouselImages:
    - name: birds
    - name: easter-ham
    - name: ham
    - name: poppers
    - name: prime-rib
    - name: ribs
    - name: ribstack
    - name: stack
    - name: tri-tip 


# Build settings
markdown: kramdown
